### ISSUE TITLE
xubuntu installed but said no EFI or something like that...

### ISSUE THREAD

**Issue by GitHub-Drorhome** [ra1nstorm/ra1nstorm-helper#10]
After the reboot for the install I don't have Xubuntu in the boot menu. I have Ubuntu which was installed on a smaller drive and does not have enough space for more apps and Windows on a second drive. How do I get Xubuntu to boot?

**Comment by andwat18** [comment]
I have the same question as above https://github.com/GitHub-Drorhome

**Comment by aurilly** [comment]
Normal, just click continue if you haven't already.
