### ISSUE TITLE
ra1nstorm failed to download macOS installer

### ISSUE THREAD

**Issue by jimmyntak** [ra1nstorm/ra1nstorm-helper#13]
Title says it all.

**Comment by CaseyCZ** [comment]
Same problem

**Comment by Garcia111907** [comment]
Same! FYI I already has my PC set up to dual boot between Win 10 and Unbuntu 19.10 so I started at step 2 (ra1nstorm.run). The terminal message says "sh: 1: ./fetch-macOS.py: not found".

**Comment by MrHomebrew** [comment]
Failed to install macOS installation img here also unfortunately.

**Comment by tlaf8** [comment]
The fetch-macOS file is written in python and it's possible that it isn't installed. I recently dual booted a fresh version of Ubuntu on my computer and it looks like it didn't install python for whatever reason. Try running `sudo apt-get install python` and you should be set. If not, I'm not sure how to fix it. 

Hopefully this helps!

**Comment by jimmyntak** [comment]
Thank you. It was python that was missing
