### ISSUE TITLE
No protocol specified

### ISSUE THREAD

**Issue by TipzTeam** [ra1nstorm/ra1nstorm-helper#132]
ricky@ricky-ThinkCentre-M92p:~/Downloads$ sudo bash ra1nstorm.run
[sudo] password for ricky: 
Verifying archive integrity...  100%   All good.
Uncompressing ra1nstorm_stage2  100%  
Checking if zenity and gawk are installed...
Launching setup...
No protocol specified
Unable to init server: Could not connect: Connection refused

(zenity:26862): Gtk-WARNING **: 16:34:11.794: cannot open display: :0

Here you go fix it ok ok ok ok bye

**Comment by ducanh2002123** [comment]
Please enter “xhost +” in the terminal window, and then “sudo bash Ra1nstorm.run”

**Comment by ducanh2002123** [comment]
This is the same issue as #79
