### ISSUE TITLE
host doesn't support requested feature: CPUID.01H:ECX.aes

### ISSUE THREAD

**Issue by if6was99** [ra1nstorm/ra1nstorm-helper#14]
Laptop CPU supports VT-d, is even enabled.
qemu) qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.aes [bit 25]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.aes [bit 25]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.aes [bit 25]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.aes [bit 25]
qemu-system-x86_64: -device vfio-pci,host=00:1d.0,bus=pcie.0: vfio error: 0000:00:1d.0: no iommu_group found: No such file or directory

**Comment by aurilly** [comment]
Try to repair VFIO in ra1nstorm.

**Comment by qixuchang** [comment]
I also have this situation, how to solve it?

**Comment by aurilly** [comment]
@qixuchang Use the repair VFIO option in ra1nstorm if you haven't already.

Otherwise, Closed due to no response in 17 days.
