### ISSUE TITLE
A problem while installing Xubuntu

### ISSUE THREAD

**Issue by xorpix** [ra1nstorm/ra1nstorm-helper#18]
I’m getting this error message:
![ABBD2E6F-16DC-4538-B866-FA00298480EE](https://user-images.githubusercontent.com/22274805/69497220-2affe580-0ee3-11ea-829a-b76f3a85b73e.jpeg)

I tried to do what’s written there and it didn’t help. My PC is Microsoft Surface Pro 6. Secure Boot is disabled. Hibernation and fast boot are disabled too.

**Comment by avatar1333** [comment]
Me too

**Comment by aurilly** [comment]
Boot back into windows and reinstall ra1nstorm completely.

**Comment by xorpix** [comment]
Won't help. Already figured out, that problem is about two SSD drives which work in Microsoft's unbreakable software RAID.

**Comment by aurilly** [comment]
Closed due to OP responding saying that he's figured it out.
