### ISSUE TITLE
BootVM.sh error

### ISSUE THREAD

**Issue by vizors** [ra1nstorm/ra1nstorm-helper#19]
Whenever I try to run bootvm.sh I get this error: 
failed to open /dev/vfio/1: No such file or directory
Any way to resolve this? Thanks

**Comment by z0mbieslayer** [comment]
I get this error too.

**Comment by aurilly** [comment]
Use the repair VFIO option in ra1nstorm if you haven't already.

Otherwise, Closed due to no response in 17 days.
