### ISSUE TITLE
Do not have permission for BootVM.sh

### ISSUE THREAD

**Issue by naldo29** [ra1nstorm/ra1nstorm-helper#20]
Everytime I drag the boot sh file, I get a screen that says that I don’t have permission. Now I was able to bypass it but when I do it now, it just shows me the script! Help. Thanks 
![57B1D809-D80D-4491-B169-68A9F0856357](https://user-images.githubusercontent.com/35706559/69498048-0ba09280-0eba-11ea-97a3-94ffbb4afbda.jpeg)
![E9894D6F-5C4C-4720-A3CC-57522BD757BF](https://user-images.githubusercontent.com/35706559/69498049-0ba09280-0eba-11ea-9410-8dda7db263b0.jpeg)

**Comment by z0mbieslayer** [comment]
leave a space after "bash"

**Comment by naldo29** [comment]
That didn’t work.... 😔

**Comment by jedzerna** [comment]
Mine also needs permission, someone help us...BootVM.sh needs permission i can’t open it..

**Comment by buchwasa** [comment]
Try doing `chmod +x BootVM.sh`

**Comment by naldo29** [comment]
![image](https://user-images.githubusercontent.com/35706559/69499781-3562b500-0ecc-11ea-9427-73517891cfda.jpg)

**Comment by naldo29** [comment]
Didn’t work.....

**Comment by buchwasa** [comment]
Add a sudo to the front of chmod and try again

**Comment by naldo29** [comment]
![image](https://user-images.githubusercontent.com/35706559/69499820-82df2200-0ecc-11ea-9deb-556699922798.jpg)
Umm what do I do now?

**Comment by buchwasa** [comment]
sudo bash BootVM.sh

**Comment by naldo29** [comment]
![image](https://user-images.githubusercontent.com/35706559/69499880-fbde7980-0ecc-11ea-8693-27fbbc8d8d92.jpg)
The famous error

**Comment by Ronsor** [comment]
This will be fixed with 0.9.2

**Comment by naldo29** [comment]
Thx

**Comment by naldo29** [comment]
Thx for fixing this so quickly and making this for the community, even if it’s so toxic lol

**Comment by code-dep** [comment]
When the version 0.9.2 will release?

**Comment by naldo29** [comment]
When the gods say “it’s time”

**Comment by code-dep** [comment]
oh ok

**Comment by Games-Crack** [comment]
try sudo chown [your username] BootVM.sh

and use: sudo /home/[Username]/Desktop/BootVM.sh

**Comment by naldo29** [comment]
![image](https://user-images.githubusercontent.com/35706559/69545348-09950d00-0f68-11ea-85cc-066d4659bef7.jpg)
It’s a pcie thing. Ronsor said.

**Comment by naldo29** [comment]
“It appears that it attempts to forward the entire PCIe bridge, rather than just the USB controller.“
