### ISSUE TITLE
xubuntu only booting into GRUB

### ISSUE THREAD

**Issue by madhvan-g** [ra1nstorm/ra1nstorm-helper#22]
When I boot into Xubuntu it only shws GNU GRUB terminal like thing, how do I boot into Xubuntu?

**Comment by Ronsor** [comment]
Try booting into Windows, shutting down properly, and then booting into Xubuntu

**Comment by madhvan-g** [comment]
Tried doing that, still boots into GRUB, tried making another partition for the install but it says the EFI partition is missing, the installation goes on and reboots into GRUB

**Comment by Games-Crack** [comment]
The boat manager (Grub) is broken you have to reinstall xubuntu and try again!

**Comment by ctalbot4** [comment]
same issue

**Comment by aurilly** [comment]
Completely reinstall xubuntu if you haven't already.

Closed due to no response in 16 days.

**Comment by ctalbot4** [comment]
I did that and it still wouldn’t boot past the GRUB command line. I pretty much gave up. It’s not that big of a deal though because I have a Mac as well, I just wanted to try this out.

**Comment by aurilly** [comment]
Alright.
