### ISSUE TITLE
Install MacOS Catalina fails with error “The operation couldn’t be completed.  (PKDownloadError error 8.)”

### ISSUE THREAD

**Issue by omin32** [ra1nstorm/ra1nstorm-helper#25]
Twice now this happened.  I googled and found this: https://discussions.apple.com/thread/250713303

It says the issue is fixed in 10.15.1.  Also in one of the comments, a user says,” I started getting this error after trying to to do a clean install of Catalina on my iMac. I entered the Recovery mode, erased the primary drive, and tried to do an install of Catalina. It would run for an hour or more and then I would get this error. I thought this may be related to my connectivity issues so I tried using different wireless networks and dragging an ethernet cable through my house to the router but with no success.

I believe repartitioning the drive was the mistake. Catalina uses a split drive setup where all of the system files are on an inaccessible system partition and the user files are on a separate partition. I believe that by creating a single partition drive the Catalina installer was unable to properly partition the disk and would stall until the Internet connection was finally dropped and the installation failed.”

**Comment by Ronsor** [comment]
I will update ra1nstorm to use version 10.15.1

**Comment by omin32** [comment]
Here are some screen shots of error and the error log.  I couldn’t fit the entire error log on the screen so I one shot is the left part and one shot is the last part
![B5F43D64-BFFD-49BB-8254-6ADF6DA021DD](https://user-images.githubusercontent.com/58152363/69503523-47922280-0ecf-11ea-82f1-cc09665f4a27.jpeg)
![D8B7DB0C-9D2B-4B8E-B620-4C28148A614E](https://user-images.githubusercontent.com/58152363/69503524-482ab900-0ecf-11ea-9cb8-db7a2ba62f30.jpeg)
![3029A040-946F-4C28-B380-7E2319598F3D](https://user-images.githubusercontent.com/58152363/69503525-482ab900-0ecf-11ea-998f-d9e6535756c2.jpeg)

**Comment by omin32** [comment]
> I will update ra1nstorm to use version 10.15.1

Thanks!!!!

**Comment by Ronsor** [comment]
> > I will update ra1nstorm to use version 10.15.1
> 
> Thanks!!!!

Just did it: version 0.92.f.
