### ISSUE TITLE
VFIO still not working

### ISSUE THREAD

**Issue by naldo29** [ra1nstorm/ra1nstorm-helper#26]
look, i tried everything, im in the latest update, i reinstalled everything, i tried the "fix" and nothing... please someone help me.
[SystemLog.txt](https://github.com/ra1nstorm/ra1nstorm-helper/files/3884279/SystemLog.txt)

**Comment by Ronsor** [comment]
Is this version 0.9.2f?

**Comment by naldo29** [comment]
that file? no but i also tried it and gave me the same result

**Comment by Ronsor** [comment]
Please try 0.9.2g, and, if it fails, send a new log.
https://github.com/ra1nstorm/ra1nstorm-helper/releases/tag/0.9.2

**Comment by naldo29** [comment]
[SystemLog.txt](https://github.com/ra1nstorm/ra1nstorm-helper/files/3884316/SystemLog.txt)

**Comment by naldo29** [comment]
it failed...

**Comment by naldo29** [comment]
im also getting the same issue that is #20 but when i force it to be one, it just shows me the script

**Comment by Ronsor** [comment]
> Please try 0.9.2g, and, if it fails, send a new log.
> https://github.com/ra1nstorm/ra1nstorm-helper/releases/tag/0.9.2

It appears that it attempts to forward the entire PCIe bridge, rather than just the USB controller.

Thank you. I will investigate a possible solution.

**Comment by naldo29** [comment]
damm, that sounds bad, i hpoe you can do it, i believe in you

**Comment by AM4Ryzen** [comment]
I have the same issue
[SystemLog.txt](https://github.com/ra1nstorm/ra1nstorm-helper/files/3884781/SystemLog.txt)

**Comment by Ronsor** [comment]
Should be fixed in 0.9.3 after a VFIO repair.
