### ISSUE TITLE
VFIO error remains....

### ISSUE THREAD

**Issue by z0mbieslayer** [ra1nstorm/ra1nstorm-helper#29]
MacOS is able to boot right after I finish installing it. But when I need to reboot for it to forward the usb controller thing, I go to start my vm, and get the vfio error. Here's my log: 
[SystemLog.txt](https://github.com/ra1nstorm/ra1nstorm-helper/files/3884428/SystemLog.txt)

**Comment by naldo29** [comment]
ayyyyy same problem
