### ISSUE TITLE
idk what this issue is its just broken

### ISSUE THREAD

**Issue by manofmanytalents** [ra1nstorm/ra1nstorm-helper#3]
[wubi-18.04.2-rev333.log](https://github.com/ra1nstorm/ra1nstorm-helper/files/3882143/wubi-18.04.2-rev333.log)

**Comment by manofmanytalents** [comment]
sorry idk techy stuff

**Comment by Ronsor** [comment]
Should be fixed in 0.9.1

**Comment by jirayutza1** [comment]
> wubi-18.04.2-rev333.log
