### ISSUE TITLE
MacOS Catalina cannot be installed

### ISSUE THREAD

**Issue by alexthedog** [ra1nstorm/ra1nstorm-helper#34]
I have followed all the steps as mentioned in the tutorial and when I erase the disk and make it like 'KVMDisk' for installing MacOS, it's showing me the error that MacOS Catalina cannot be installed as it's unable to download the necessary files or something! Please help.

**Comment by alexthedog** [comment]
![macOS](https://user-images.githubusercontent.com/58161791/69518812-ad8bb200-0f82-11ea-8b86-0f93dd68e263.png)

I can't find option to install MacOS, it just shows this menu. Please help!

**Comment by DeltaOn3X** [comment]
Choose Reinstall macOS and try it again.

**Comment by alexthedog** [comment]
> Choose Reinstall macOS and try it again.

I tried that, but it again gives me the error that MacOS Catalina cannot be installed as it's unable to download the necessary files.

**Comment by DeltaOn3X** [comment]
Can you screenshot it please ?

**Comment by alexthedog** [comment]
> Can you screenshot it please ?

I don't have the screenshot right now as I decided to try it again with the latest update of ra1nstorm, if the error appears again, I'll share the screenshot. Meanwhile, if you come up with any solution, please share!

**Comment by aurilly** [comment]
Try using an Ethernet cord instead of WiFi.

If that doesn't work, create a new issue.

Closed due to no response in 16 days.
