### ISSUE TITLE
MacOS not detecting iPhone?!

### ISSUE THREAD

**Issue by DrazzyXD** [ra1nstorm/ra1nstorm-helper#40]
After I boot my macos, I get this black screen with white text. it recognised my keyboard and mouse, but not my iphone. I even checked my iphone to see if its connected, but it was not detecting the iphone. Help is appreciated.
[SystemLog.txt](https://github.com/ra1nstorm/ra1nstorm-helper/files/3889003/SystemLog.txt)

![IMG_0426](https://user-images.githubusercontent.com/58153114/69582943-b3e05500-0fa7-11ea-9b63-3ff31d9e092c.JPG)

**Comment by DrazzyXD** [comment]
the ra1nstorm.run version is 0.9.3 and I constantly repaired the USB/VFIO so many times. I even tried to switch my iphone charging cable to other ports, yet it doesn't detect the iphone. Again, help is appreciated.

**Comment by jesse0001** [comment]
I have the same promblem please help

**Comment by DrazzyXD** [comment]
This is my macos and the CheckRa1n program and it's not detecting my iphone connection.

![IMG_0427](https://user-images.githubusercontent.com/58153114/69588349-56073980-0fb6-11ea-99b7-bae92d8de717.JPG)

**Comment by abra82** [comment]
I too have this problem but on 0.9.5. Looks to be the last bit before jailbreak............ouch!

**Comment by DrazzyXD** [comment]
Just downloaded the latest ra1nstorm.run (0.9.4) and ran the USB/VFIO fix and MacOS still does not detect the iPhone. If it helps, im using an iPhone SE.
![IMG_0429](https://user-images.githubusercontent.com/58153114/69678990-09366800-1075-11ea-8921-2d17ff6b4025.JPG)

**Comment by kaoticvisual** [comment]
I’m having the same issue. Iv used ra1nstorm 9.0, 9.1, 9.2, 9.3, and 9.4. Iv used USB/VFIO fix on all of them. Even used checkra1n 9.4 , and 9.5. Still not being recognized. Even installed mac 2x and Linux 2x as well. It’s just not being recognized.

**Comment by sayelet** [comment]
https://www.youtube.com/watch?v=gSiNiZrTE1I
I think this can be solved.

**Comment by kaoticvisual** [comment]
I don’t understand Spanish, but based on the video. Iv done all that to the t on all ra1nstorm ver. Thank you tho. Unless he is saying something in spanish, I’m not sure.

**Comment by DrazzyXD** [comment]
@Ronsor I need to know if this is an issue on my end because I have repaired the USB/VFIO countless amount of times, and I have tried every USB port and the macos still does not detect the iphone, but it detects my mouse and keyboard. I updated to 0.9.4b btw

**Comment by DrazzyXD** [comment]
btw, this problem has been going on for 2 days.

**Comment by abra82** [comment]
Has anyone managed to figure a way past this yet? Is it linked to the IOMMU/VT-d failure? These appear to be the 2 main issues for me.

**Comment by ZuhnK1tty** [comment]
Same problem for me no phone connection

**Comment by Epunch** [comment]
Same problem on iphone x.  That Spanish video doesn’t help me. And fake. Plz someone help us. Jesus Christ.

**Comment by Aliaptx40** [comment]
try this video
https://www.youtube.com/watch?v=k8ktfgOv_Vg

he got the iphone working

**Comment by Aliaptx40** [comment]
this one too but is in arabic
https://www.youtube.com/watch?v=Lbu7d0Gupxw

**Comment by kaoticvisual** [comment]
Still no detection.

**Comment by Epunch** [comment]
I received an error  when I type:
Sudo gedit /etc/default/grub
