### ISSUE TITLE
Stuck on Locating USB Controller.

### ISSUE THREAD

**Issue by ktzug** [ra1nstorm/ra1nstorm-helper#41]
Hey everyone! I've wanted to jailbreak my old iPod Touch 6G for a while but I don't own a Mac and can't hackintosh due to no ownership of USB, so I tried ra1nstorm.
Everything went fine until ra1nstorm had to locate my USB controller, which unfortunately didn't work. and had to restart ra1nstorm several times (because when I clicked Back it crashed for no reason) 
Thing is, xubuntu recognizes my iPod. Yes, I trusted the computer; Yes, I did go to lsusb just to see if xubuntu actually recognizes it (it does recognize it as an iPod Touch 5G but that's off-topic); And Terminal returns this error 
> ls: cannot access 'sys/bus/usb/drivers/ipheth/*:*: No such file or directory debug! pcidd=

Any help would be appreciated!

**Comment by Ronsor** [comment]
This will be fixed in 0.9.4

**Comment by timonline** [comment]
I am running 0.9.5 and still see this problem
