### ISSUE TITLE
Won’t let me go into Ubuntu for a second time

### ISSUE THREAD

**Issue by N3V3RDIE1** [ra1nstorm/ra1nstorm-helper#46]
Black screen with text when reboot
![image](https://user-images.githubusercontent.com/58214992/69624367-909ebf80-1012-11ea-8182-ab8e8c54ee03.jpg)

**Comment by N3V3RDIE1** [comment]
Fixed it nevermind

**Comment by yaf3i** [comment]
How did you fix it ?

**Comment by iDeviceable** [comment]
yes, please explain how you fixed it. The same exact thing happened to me.
