### ISSUE TITLE
mac os version : not yet set

### ISSUE THREAD

**Issue by Pwn0day** [ra1nstorm/ra1nstorm-helper#48]
i have problem when i finished setup this screen restart and back to clover again and again 
![F3D6D7EB-95A7-4687-BED6-E3CA60B2DCAC](https://user-images.githubusercontent.com/42302310/69643458-0be08f80-106c-11ea-93f9-98b901a80cc3.jpeg)

**Comment by Ronsor** [comment]
That is a kernel panic. Your hardware may not be compatible with macOS, but you can try reinstalling.
