### ISSUE TITLE
This computer does not have an Intel CPU" but I have an Intel Core i5

### ISSUE THREAD

**Issue by mokhtarDZ27** [ra1nstorm/ra1nstorm-helper#49]
I steal have : "This computer does not have an Intel CPU" with ra1nstorm 0.9.3

**Comment by mokhtarDZ27** [comment]
![picture](https://user-images.githubusercontent.com/58226748/69654942-eb1d3780-1075-11ea-93a7-822b326743ec.png)

**Comment by Ronsor** [comment]
That error was completely dropped in 0.9.3. You must download the latest version using the link below:

https://github.com/ra1nstorm/ra1nstorm-helper/releases/tag/0.9.3
