### ISSUE TITLE
"This computer does not have an Intel CPU" but I have an Intel Core i7-9750H

### ISSUE THREAD

**Issue by DocSystem** [ra1nstorm/ra1nstorm-helper#5]
All is in the title

Here is a screenshot of ra1nstorm installer and About Settings page
![Screenshot](https://user-images.githubusercontent.com/42613513/69477897-1db3ff80-0dec-11ea-810d-826107b6c954.png)

**Comment by Ronsor** [comment]
Will be fixed in latest update
