### ISSUE TITLE
"An Internet connection is required to install macOS"

### ISSUE THREAD

**Issue by shrayus-masanam** [ra1nstorm/ra1nstorm-helper#52]
I'm on Linux Mint and connected via ethernet but the macOS installer doesn't seem to be connected

**Comment by DrazzyXD** [comment]
I recommend not using Linux Mint because I also had this issue where the MacOS was not detecting the internet connection

**Comment by DrazzyXD** [comment]
Use Ubuntu and Xubuntu as this will most likely resolve this issue

**Comment by shrayus-masanam** [comment]
Okay thanks I'll try it out

**Comment by Volkezz** [comment]
I am on Ubuntu and it gives me that error!

**Comment by shrayus-masanam** [comment]
This worked for me
