### ISSUE TITLE
Bootvm.sh doesn’t show on desktop 

### ISSUE THREAD

**Issue by just01guy** [ra1nstorm/ra1nstorm-helper#59]
Hello I installed xubuntu and did everything as described. But I have some problems
1) when I hit enter after writing cd Desktop it can’t find such file or directory 
2) when everything is ready (without cd Desktop) it doesn’t show bootvm.sh and I can’t run vm again after restart 
Please help me to fix this problems. Thank you.

**Comment by mokhtarDZ27** [comment]
Same problem for me !

**Comment by Jakob333** [comment]
Literally all you have to do is look it up in files and it will be there. If not you can download the  stage2 from the GitHub and then use then use bootvm.sh from the folder.

**Comment by mokhtarDZ27** [comment]
Thanks it’s work :)

**Comment by just01guy** [comment]
Thanks for the help.

**Comment by qixuchang** [comment]
me too

**Comment by aurilly** [comment]
Closed due to OP and user with same issue saying it has been solved.
