### ISSUE TITLE
USB’s not passed through

### ISSUE THREAD

**Issue by termz64** [ra1nstorm/ra1nstorm-helper#6]
I have installed everything and have Mac OS running with checkra1n installed. However nothing from my USB ports open in Mac. They all open in ubuntu still. This is right from the installation. How do I start the vm with the USB’s passed through?

**Comment by Ronsor** [comment]
Did you remember to plug in your iPhone at the USB passthrough step?

**Comment by termz64** [comment]
What USB passthrough step? Whoops

**Comment by Ronsor** [comment]
It happens after you finish installing macOS.

You will be prompted to plug in your iPhone for USB controller detection./

**Comment by termz64** [comment]
I did not see that pop up. How can I fix this?
