### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by vodkya** [ra1nstorm/ra1nstorm-helper#61]
When I click the "install" button it starts, then gives this error.
"An error encountered:

No such file or directory

For more info please see the log file"

Please help me with this!
Log file below.
[wubi-18.04.2-rev333.log](https://github.com/ra1nstorm/ra1nstorm-helper/files/3898589/wubi-18.04.2-rev333.log)

**Comment by ilyastray777** [comment]
В жопу вас нихрена у вас не работает, программисты из серии «и таааак сойдёт! А есть вы тоже за меня будете? Агаааа!»

**Comment by ilyastray777** [comment]
ye xt

**Comment by ilyastray777** [comment]
ну че

**Comment by alapaches** [comment]
> When I click the "install" button it starts, then gives this error.
> "An error encountered:
> 
> No such file or directory
> 
> For more info please see the log file"
> 
> Please help me with this!
> Log file below.
> [wubi-18.04.2-rev333.log](https://github.com/ra1nstorm/ra1nstorm-helper/files/3898589/wubi-18.04.2-rev333.log)

Hi mate,
Examined the log and it appears your wubi.exe isn't in the right folder.

It is in"C:\\Users\\fang2\\AppData\\Local\\Temp\\is-C159C.tmp\\ra1nlinux"

It should be in "C:\\Users\\fang2\\AppData\\Local\\ra1nlinux"

I suggest you delete ra1nlinux from your appdata and from your temp folder and run setup.exe.

It should solve the problem

**Comment by vodkya** [comment]
Ok. Thank you. I’ll try that.

**Comment by vodkya** [comment]
It worked!
