### ISSUE TITLE
how do I run xubuntu?

### ISSUE THREAD

**Issue by manofmanytalents** [ra1nstorm/ra1nstorm-helper#7]
i ran the setup.exe and i finished it, all was well but when the time came to restart my computer, i did it and Windows just opened up normally.

**Comment by Ronsor** [comment]
You have to access the boot menu. When you start up your computer, you will have to press a specific key to access it. This key varies by computer, but try F12, F9, or ESC.

After that, you may select Xubuntu from the menu.

**Comment by manofmanytalents** [comment]
Thanks. Just figured out I have a novo button. Now I just need to figure out how to connect to the internet on xubuntu, its like the whole OS is a puzzle

**Comment by manofmanytalents** [comment]
I can’t figure out how to connect to the internet. 
![image](https://user-images.githubusercontent.com/36655368/69485390-a71b0000-0df3-11ea-84cc-59af2caee5c4.jpg)

Google hasn’t helped.

**Comment by Ronsor** [comment]
It appears you need to connect over Ethernet to download necessary firmware for your WiFi card

**Comment by aurilly** [comment]
Closed due to no response in 3 days, looks like it's cleared up.
