### ISSUE TITLE
6 gb ram required

### ISSUE THREAD

**Issue by kugame** [ra1nstorm/ra1nstorm-helper#72]
beta is asking for minimum 6 gb of ram 
pls help me

**Comment by Jakob333** [comment]
Do you have more than 6 gigabytes of ram?

**Comment by kugame** [comment]
no is it required

**Comment by kugame** [comment]
> Do you have more than 6 gigabytes of ram?

no is it required

**Comment by Jakob333** [comment]
you need 6 gigs or more

**Comment by kugame** [comment]
> you need 6 gigs or more

ok that means I have to wait for the original version of windows
