### ISSUE TITLE
After rebooting problem

### ISSUE THREAD

**Issue by kugame** [ra1nstorm/ra1nstorm-helper#75]
![image](https://user-images.githubusercontent.com/58380253/69913003-f0082f80-1457-11ea-9ea5-ecce41d0a0c9.jpg)
My pc got freezes when I run rainstorm.run then I rebooted it after that it is showing this pls help

**Comment by HuskyGit** [comment]
So you need to type exit and it is going to try to exit and will probably fail. It may ask you to run fsck to /???/??? And than do the command they ask you to do. When you successfully done that you type exit again.
